### PR TITLE
update multinic filter to pick only pci devices

### PR DESCRIPTION
**Pull request by polytan**
Verified there are some docker interfaces that was not excluded from the filter, this change aim to just setup IRQ for pci devices.

### CODE REVIEW

**Comment by a-crate** [comment]
Excluding `/sys/devices/virtual` seems more in line with the original filter intent than only including pci devices, and should still exclude docker's NIC. I'm not aware of any non-pci NICs that need to be included but I'm hesitant about making new assumptions without supporting reasons.

/ok-to-test

**Comment by dorileo** [comment]
@a-crate 

Do you mean doing  `grep -v /sys/devices/virtual` rather than `grep '/sys/devices/pci'`?

**Comment by a-crate** [comment]
Yes, exactly.

**Comment by polytan** [comment]
I might not expert, but will it has other type of devices here? I assume we have, but above change applies for A3 only: https://github.com/GoogleCloudPlatform/guest-configs/blob/master/src/usr/bin/google_set_multiqueue#L212
```
if ! is_a3_platform; then
  exit
fi
```

A3 NICs are under PCIe switch, that's why I'm prefer `grep '/sys/devices/pci'`.

**Comment by a-crate** [comment]
Seems reasonable enough to do this only on A3. I am not an approver for this repo anyway, Leo will need to give the ok as well before merge.
/lgtm

**Pull request merged**
