### PR TITLE
dont set IP in etc/hosts; remove rsyslog

### PR DESCRIPTION
**Pull request by hopkiw**
* Set hostname entry to always use 127.0.0.2
* Remove all rsyslog-related code except for the exit hook restart
* Don't care if nmcli or rsyslog restart fail (this script must not fail)

### CODE REVIEW

**Comment by donjaime** [comment]
@hopkiw we have some evidence that this is causing problems for services starting on VMs where this new etc host rule is in place. Instead of binding to the GCP internal IP, processes end up binding to this loopback address. Preventing communication from other VMs. What was the motivation behind this `/etc/hosts` change? Thanks!

**Comment by donjaime** [comment]
This is actually really really bad for systems that publish their individual hostnames for service discovery (even if they bind to 0.0.0.0). We've seen processes publishing the loopback address despite binding their ports externally. We've had to revert `/usr/bin/google_set_hostname` and the modified `/etc/hosts` on any VM that pulled in this update. This is a super disruptive update!

**Comment by ahzaz** [comment]
We are also seeing similar issues with hdfs namenode service where it publishes to loopback address instead of internal IP.

**Comment by donjaime** [comment]
@hopkiw @zmarano just to restate the impact. This update is completely breaking many *very heavily used* distributed systems that run on VMs. More systems will break as people update their packages. Can this be rolled back?

**Comment by chrisboulton** [comment]
We are seeing the same as @donjaime, and at the moment I'm in a bit of disbelief that a change like this was able to be landed down into this package without more scrutiny. Coupled with OS patching/unattended updates this is slowly rolling through our environment right now and breaking critical workloads.

**Comment by revident** [comment]
To expand the scope of breakage, anything relying on forward and reverse dns lookups to match are impacted. Postgres is an example that only allows host names in configurations forward/resverse lookup pair match.

An alternative is not creating this line at all.

**Comment by zmarano** [comment]
Thanks for this information! That is immensely helpful and certainly explains the utility.

We have reverted this change and there are new packages rolled out with the reverted change (versioned 20210916.00-g1). We are in process of updating the base images for Debian, CentOS, RHEL, and Rocky Linux that were released yesterday which also included this change.

**Comment by hopkiw** [comment]
@donjaime thanks for your feedback here and I hope the rollback was able to resolve any impact on your end. We're looking to understand this issue better to avoid in the future - could you provide any technical details in #29 that might help us understand? Specifically around what behavior you saw with which software, so we can reproduce it on our end.

**Comment by donjaime** [comment]
@hopkiw yes the patch worked for us. We have been able to update packages without breaking systems. And will do. Posting some more detailed notes on #29 now. Thanks!

**Pull request merged**
